<?php

/**
 * This file is automatically generated. Use 'arc liberate' to rebuild it.
 *
 * @generated
 * @phutil-library-version 2
 */
phutil_register_library_map(array(
  '__library_version__' => 2,
  'class' => array(
    'AbstractXUnitTestEngine' => 'unit/engine/AbstractXUnitTestEngine.php',
    'AnsibleLintLinter' => 'lint/linters/AnsibleLintLinter.php',
    'CheckstyleLinter' => 'lint/linters/CheckstyleLinter.php',
    'DetektLinter' => 'lint/linters/DetektLinter.php',
    'GradleUnitTestEngine' => 'unit/engine/GradleUnitTestEngine.php',
    'MavenUnitTestEngine' => 'unit/engine/MavenUnitTestEngine.php',
    'TerraformFmtLinter' => 'lint/linters/TerraformFmtLinter.php',
  ),
  'function' => array(),
  'xmap' => array(
    'AbstractXUnitTestEngine' => 'ArcanistUnitTestEngine',
    'AnsibleLintLinter' => 'ArcanistExternalLinter',
    'CheckstyleLinter' => 'ArcanistExternalLinter',
    'DetektLinter' => 'ArcanistExternalLinter',
    'GradleUnitTestEngine' => 'AbstractXUnitTestEngine',
    'MavenUnitTestEngine' => 'AbstractXUnitTestEngine',
    'TerraformFmtLinter' => 'ArcanistExternalLinter',
  ),
));
