#!/bin/bash

# Creates symlinks for git hooks in .git/hooks directory for the current project.
# Running this script is usually done with the 'init' make target which should be part of the repo.

ORIGIN_PATH=`pwd`
SCRIPT_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEV_HOME="$SCRIPT_PATH"/..
GIT_HOOKS_PATH="$DEV_HOME"/git-hooks

if [[ $(git rev-parse --is-inside-work-tree) == "true" ]]; then
  cd $SCRIPT_PATH
  git pull 1> /dev/null
  cd $ORIGIN_PATH
  _git_dir=$(git rev-parse --git-dir)
  find $_git_dir/hooks -type l -exec rm {} \;
  find $GIT_HOOKS_PATH -type f -exec ln -sf {} $_git_dir/hooks/ \;
else
  echo "Error: This script should only be used from a git repo."
  exit 1
fi
