#!/bin/bash

RESTORE_PATH=`pwd`
#SCRIPT_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/$(basename "${BASH_SOURCE[0]}")"
SCRIPT_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

if [ ! -z "$SCRIPT_PATH" ]
then
  cd "$SCRIPT_PATH/../lib"

  if [ -f "detekt.jar" ]
  then
    java -jar detekt.jar $*
  else
    echo 'detekt.jar can not be found'
  fi

  cd "$RESTORE_PATH"
else
  echo 'Path pointing to right script directory can not be found'
fi
