#!/bin/bash
if git tag > /dev/null 2>&1 && [ $? -eq 0 ]; then
  echo "You're executing git-mirror script inside another repository."
  echo "This can cause unpredictable results, please change to a non-git repo."
  exit 1
fi

git clone --mirror $1
dirName=$(basename $1)
cd $dirName
git push --mirror $2
