#!/bin/bash
RESTORE_PATH=`pwd`
SCRIPT_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_CHECKSTYLE="checkstyle/repo"
REPO_DETEKT="detekt/repo"

if [ "$1" = "upgrade" ]
then
  cd "$SCRIPT_PATH" || exit 1
  cd ".."
  git pull
  # checkstyle
  git clone https://github.com/checkstyle/checkstyle.git "$REPO_CHECKSTYLE" 2> /dev/null || (cd "$REPO_CHECKSTYLE" || exit 1; git pull)
  cd $REPO_CHECKSTYLE || exit 1
  mvn -DskipTests package
  cd ..
  rm $REPO_CHECKSTYLE/target/*tests.jar
  ln -s $REPO_CHECKSTYLE/target/`ls -rt $REPO_CHECKSTYLE/target | tail -n1` checkstyle.jar
  cd ..
  # detekt
  git clone https://github.com/arturbosch/detekt.git "$REPO_DETEKT" 2> /dev/null || (cd "$REPO_DETEKT" || exit 1; git pull)
  cd $REPO_DETEKT || exit 1
  ./gradlew build -x test
  cd ..
  ln -s $REPO_DETEKT/build/libs/`ls -rt $REPO_DETEKT/build/libs | tail -n1` detekt.jar
  cd ..
  # Wrap-up
  cd "$RESTORE_PATH" || exit 1
else
  echo "Usage:"
  echo "upgrade: Upgrade the dev-phabricator repository from source"
  echo "help:    These help instructions"
fi
